apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
  - name: "kuard-data"
    hostPath: # hostPath create a directory on the host machine at specified path
      path: "/var/lib/kuard"
    # nfs: # nfs are managed as well
    #   server: my.nfs.server.local
    #   path: "/exports"
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    volumeMounts:
    - mountPath: "/data"
      name: "kuard-data"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
