apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
spec:
  containers:
    - name: kuard-secret
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      command:
        - "/kuard"
        - "$(EXTRA_PARAM)"
        - "$(BIG_BIG_PARAM)"
      env:
        - name: ANOTHER_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: another-param
        - name: EXTRA_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
        - name: BIG_BIG_PARAM
          value: bigeuh
      volumeMounts:
        - name: config-volume
          mountPath: /lib/config
        - name: tls-certs
          mountPath: "/tls"
          readOnly: true
  imagePullSecrets:
    - name: my-image-pull-secret
  volumes:
    - name: config-volume
      configMap:
        name: my-config
    - name: tls-certs
      secret:
        secretName: kuard-tls
  restartPolicy: Never
