apiVersion: v1
kind: Pod
metadata:
  name: vapspy
spec:
  containers:
  - image: docker.io/amasson42/vapor-spy:1.0.1
    name: vapspy
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
