apiVersion: apps/v1
kind: Deployment
metadata:
  name: wa-mongo-deployment
  labels:
    app: wa-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wa-mongo
  template:
    metadata:
      labels:
        app: wa-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: wa-mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wa-mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: wa-mongo-service
spec:
  selector:
    app: wa-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
