apiVersion: apps/v1
kind: Deployment
metadata:
  name: wa-webapp-deployment
  labels:
    app: wa-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wa-webapp
  template:
    metadata:
      labels:
        app: wa-webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: wa-mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: wa-mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: wa-mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: wa-webapp-service
spec:
  type: NodePort
  selector:
    app: wa-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100 # Open on external kubernetes node port [30000-32767]
